In [53]:
import pandas as pd

import numpy as np

import glob

import openpyxl

import warnings
warnings.simplefilter("ignore")

In [54]:
#getting all the required files from the location

path = r'C:/Users/agheorghitoiu/Downloads/Google Analytics'

all_files = glob.glob(path + '/*.xlsx')

li = []

In [55]:
#concatening the files by the specified sheet name

for filename in all_files:
    df = pd.read_excel(filename, index_col=None, header=0, sheet_name='Dataset1')
    li.append(df)
    
frame =pd.concat(li, axis=0, ignore_index=True)

In [56]:
#checking the newly resulted dataframe

frame

,Page,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value
0,community.rws.com/product-groups/trados-portfo...,9655,8091,81.382176,8038,0.833561,0.810564,0.000000
1,appstore.rws.com/,6151,1716,52.535110,526,0.001931,0.048447,0.000000
2,community.rws.com/search,4372,2656,80.461514,1674,0.418106,0.277905,0.000000
3,community.rws.com/,3546,2552,78.501550,1295,0.414484,0.272420,0.000000
4,community.rws.com/product-groups/trados-portfo...,1337,641,75.017007,269,0.198502,0.120419,0.000000
...,...,...,...,...,...,...,...,...
18809,trados.com/video/transform-team-translation-wi...,1,1,5.000000,0,0.000000,0.000000,0.000000
18810,trados.com/video/transform-team-translation-wi...,1,1,42.000000,0,0.000000,0.000000,0.000000
18811,trados.com/video/using-machine-translation-mt-...,1,1,21.000000,1,0.000000,0.000000,0.000000
18812,trados.com/video/whats-new-in-trados-studio-20...,1,1,31.000000,0,0.000000,0.000000,0.000000
18813,NaN,133571,102109,118.470343,48161,0.617236,0.360565,0.109093

In [57]:
#getting more info about the dataframe with the .describe() method

frame.describe()

,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value
count,18814.000000,18814.000000,18814.000000,18814.000000,18814.000000,18814.000000,18814.000000
mean,35.497768,27.136441,131.471283,12.799245,0.283646,0.396895,0.076595
std,1949.754231,1490.224212,245.960725,704.812548,0.413161,0.408867,5.650364
min,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000
50%,2.000000,1.000000,29.000000,1.000000,0.000000,0.333333,0.000000
75%,4.000000,3.000000,141.000000,2.000000,0.666667,0.830024,0.000000
max,133571.000000,102109.000000,2778.000000,48161.000000,3.000000,1.000000,711.066288

In [58]:
#creating a new column containing labels for the URLs
#after checking the dataframe, the expressions below contain most of the groups
#a condition list was created and also a choice list, to match a condition with a choice, e.g. trados with Language Technology, tridion with Content Management

condlist = [
    frame['Page'].str.contains('.*trados', na=False),
    frame['Page'].str.contains('.*translation_management', na=False),
    frame['Page'].str.contains('.*translationproductivity', na=False),
    frame['Page'].str.contains('.*linguistic-ai', na=False), 
    frame['Page'].str.contains('.*tridion', na=False),
    frame['Page'].str.contains('.*contenta', na=False),
]

choicelist = ['Language Technology', 'Language Technology', 'Language Technology', 'Artficial Intelligence', 'Content Management', 'Content Management']

frame['Product_Group'] = np.select(condlist, choicelist)

frame

,Page,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value,Product_Group
0,community.rws.com/product-groups/trados-portfo...,9655,8091,81.382176,8038,0.833561,0.810564,0.000000,Language Technology
1,appstore.rws.com/,6151,1716,52.535110,526,0.001931,0.048447,0.000000,0
2,community.rws.com/search,4372,2656,80.461514,1674,0.418106,0.277905,0.000000,0
3,community.rws.com/,3546,2552,78.501550,1295,0.414484,0.272420,0.000000,0
4,community.rws.com/product-groups/trados-portfo...,1337,641,75.017007,269,0.198502,0.120419,0.000000,Language Technology
...,...,...,...,...,...,...,...,...,...
18809,trados.com/video/transform-team-translation-wi...,1,1,5.000000,0,0.000000,0.000000,0.000000,Language Technology
18810,trados.com/video/transform-team-translation-wi...,1,1,42.000000,0,0.000000,0.000000,0.000000,Language Technology
18811,trados.com/video/using-machine-translation-mt-...,1,1,21.000000,1,0.000000,0.000000,0.000000,Language Technology
18812,trados.com/video/whats-new-in-trados-studio-20...,1,1,31.000000,0,0.000000,0.000000,0.000000,Language Technology
18813,NaN,133571,102109,118.470343,48161,0.617236,0.360565,0.109093,0

In [59]:
#filtering results only from community.rws.com

views = frame[frame['Page'].str.contains('.*community.rws.com', na=False)]

views

,Page,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value,Product_Group
0,community.rws.com/product-groups/trados-portfo...,9655,8091,81.382176,8038,0.833561,0.810564,0.0,Language Technology
2,community.rws.com/search,4372,2656,80.461514,1674,0.418106,0.277905,0.0,0
3,community.rws.com/,3546,2552,78.501550,1295,0.414484,0.272420,0.0,0
4,community.rws.com/product-groups/trados-portfo...,1337,641,75.017007,269,0.198502,0.120419,0.0,Language Technology
5,community.rws.com/product-groups/trados-portfo...,1210,838,91.080208,248,0.423529,0.206612,0.0,Language Technology
...,...,...,...,...,...,...,...,...,...
17027,community.rws.com/products-solutions/sdl-tridi...,1,1,23.000000,1,0.000000,0.000000,0.0,Content Management
17028,community.rws.com/s/article/Translation-Memori...,1,1,0.000000,1,1.000000,1.000000,0.0,0
17029,community.rws.com/tags/Regex+Match+AutoSuggest...,1,1,52.000000,0,0.000000,0.000000,0.0,0
17030,community.rws.com/user,1,1,29.000000,0,0.000000,0.000000,0.0,0
17031,community.rws.com/user/$core_v2_encodingAttrib...,1,1,3.000000,0,0.000000,0.000000,0.0,0

In [60]:
#creating a new dataframe with an additional column with the hardcoded month and year

monthly_views = views.assign(month_year='Jan 2023')

monthly_views

,Page,Pageviews,Unique Pageviews,Avg. Time on Page,Entrances,Bounce Rate,% Exit,Page Value,Product_Group,month_year
0,community.rws.com/product-groups/trados-portfo...,9655,8091,81.382176,8038,0.833561,0.810564,0.0,Language Technology,Jan 2023
2,community.rws.com/search,4372,2656,80.461514,1674,0.418106,0.277905,0.0,0,Jan 2023
3,community.rws.com/,3546,2552,78.501550,1295,0.414484,0.272420,0.0,0,Jan 2023
4,community.rws.com/product-groups/trados-portfo...,1337,641,75.017007,269,0.198502,0.120419,0.0,Language Technology,Jan 2023
5,community.rws.com/product-groups/trados-portfo...,1210,838,91.080208,248,0.423529,0.206612,0.0,Language Technology,Jan 2023
...,...,...,...,...,...,...,...,...,...,...
17027,community.rws.com/products-solutions/sdl-tridi...,1,1,23.000000,1,0.000000,0.000000,0.0,Content Management,Jan 2023
17028,community.rws.com/s/article/Translation-Memori...,1,1,0.000000,1,1.000000,1.000000,0.0,0,Jan 2023
17029,community.rws.com/tags/Regex+Match+AutoSuggest...,1,1,52.000000,0,0.000000,0.000000,0.0,0,Jan 2023
17030,community.rws.com/user,1,1,29.000000,0,0.000000,0.000000,0.0,0,Jan 2023
17031,community.rws.com/user/$core_v2_encodingAttrib...,1,1,3.000000,0,0.000000,0.000000,0.0,0,Jan 2023

In [61]:
#creating an Excel file based on the newly resulted dataframe

writer = pd.ExcelWriter('Google_Analytics_Views_Jan2023.xlsx',
                       engine='xlsxwriter',
                       engine_kwargs={'options': {'strings_to_urls':False}}
                       )
monthly_views.to_excel(writer)

writer.close()